[package]
name = "file_server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
futures = "0.3"
tokio = { version = "1.39.1", features = ["full"] }
tokio-macros = { version = "2.4.0" }
local-ip-address = "0.6.1"                          # 获取本机的私有IP地址
